name: Daily Commit

on:
  schedule:
    - cron: "0 9 * * *"   # Roz 9 bajey morning par chalega (UTC time hota hai)
  workflow_dispatch:       # Manual run button bhi hoga

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set Git user
        run: |
          git config --global user.name "AREEBA-FATIMA"
          git config --global user.email "areebafatima2457@gmail.com"

      - name: Make a commit
        run: |
          echo "Auto update on $(date)" >> log.txt
          git add .

          # Random commit messages
          COMMIT_MSGS=("update: project dependencies" "fix: minor bug" "docs: updated README" "refactor: code improvements" "chore: daily maintenance")
          git commit -m "${COMMIT_MSGS[$RANDOM % ${#COMMIT_MSGS[@]}]}"
          git push
